// Static map for common Dutch grocery ingredients — used as fast cache.
// Unknown ingredients fall through to Claude API categorization.
const INGREDIENT_CATEGORY_MAP: Record<string, string> = {
  // Groente & Fruit — groenten
  ui: "Groente & Fruit",
  uien: "Groente & Fruit",
  knoflook: "Groente & Fruit",
  tomaat: "Groente & Fruit",
  tomaten: "Groente & Fruit",
  trostomaten: "Groente & Fruit",
  kerstomaten: "Groente & Fruit",
  cherrytomaten: "Groente & Fruit",
  paprika: "Groente & Fruit",
  "rode paprika": "Groente & Fruit",
  "gele paprika": "Groente & Fruit",
  "groene paprika": "Groente & Fruit",
  wortel: "Groente & Fruit",
  wortelen: "Groente & Fruit",
  wortels: "Groente & Fruit",
  winterwortel: "Groente & Fruit",
  aardappel: "Groente & Fruit",
  aardappelen: "Groente & Fruit",
  aardappels: "Groente & Fruit",
  "zoete aardappel": "Groente & Fruit",
  komkommer: "Groente & Fruit",
  courgette: "Groente & Fruit",
  broccoli: "Groente & Fruit",
  bloemkool: "Groente & Fruit",
  spinazie: "Groente & Fruit",
  champignons: "Groente & Fruit",
  champignon: "Groente & Fruit",
  paddenstoelen: "Groente & Fruit",
  prei: "Groente & Fruit",
  sperziebonen: "Groente & Fruit",
  boontjes: "Groente & Fruit",
  snijbonen: "Groente & Fruit",
  tuinbonen: "Groente & Fruit",
  capucijners: "Groente & Fruit",
  aubergine: "Groente & Fruit",
  selderij: "Groente & Fruit",
  bleekselderij: "Groente & Fruit",
  knolselderij: "Groente & Fruit",
  doperwten: "Groente & Fruit",
  mais: "Groente & Fruit",
  pompoen: "Groente & Fruit",
  butternut: "Groente & Fruit",
  andijvie: "Groente & Fruit",
  witlof: "Groente & Fruit",
  rucola: "Groente & Fruit",
  sla: "Groente & Fruit",
  ijsbergsla: "Groente & Fruit",
  veldsla: "Groente & Fruit",
  kropsla: "Groente & Fruit",
  "rode kool": "Groente & Fruit",
  "witte kool": "Groente & Fruit",
  spruitjes: "Groente & Fruit",
  spruiten: "Groente & Fruit",
  boerenkool: "Groente & Fruit",
  savooiekool: "Groente & Fruit",
  pak choi: "Groente & Fruit",
  "pak choi": "Groente & Fruit",
  paksoi: "Groente & Fruit",
  taugé: "Groente & Fruit",
  tauge: "Groente & Fruit",
  radijs: "Groente & Fruit",
  venkel: "Groente & Fruit",
  asperges: "Groente & Fruit",
  artisjok: "Groente & Fruit",
  olijven: "Groente & Fruit",
  kappertjes: "Groente & Fruit",
  "rode biet": "Groente & Fruit",
  bieten: "Groente & Fruit",
  pastinaak: "Groente & Fruit",
  koolrabi: "Groente & Fruit",
  rabarber: "Groente & Fruit",
  chilipeper: "Groente & Fruit",
  jalapeño: "Groente & Fruit",
  jalapeno: "Groente & Fruit",
  pepertje: "Groente & Fruit",
  "rode peper": "Groente & Fruit",
  bosui: "Groente & Fruit",
  bosuitjes: "Groente & Fruit",
  "lente-ui": "Groente & Fruit",
  "rode ui": "Groente & Fruit",
  sjalot: "Groente & Fruit",
  sjalotten: "Groente & Fruit",
  gember: "Groente & Fruit",
  // Groente & Fruit — fruit
  appel: "Groente & Fruit",
  appels: "Groente & Fruit",
  banaan: "Groente & Fruit",
  bananen: "Groente & Fruit",
  peer: "Groente & Fruit",
  peren: "Groente & Fruit",
  sinaasappel: "Groente & Fruit",
  sinaasappels: "Groente & Fruit",
  mandarijn: "Groente & Fruit",
  mandarijnen: "Groente & Fruit",
  citroen: "Groente & Fruit",
  citroenen: "Groente & Fruit",
  limoen: "Groente & Fruit",
  limoenen: "Groente & Fruit",
  druiven: "Groente & Fruit",
  aardbei: "Groente & Fruit",
  aardbeien: "Groente & Fruit",
  framboos: "Groente & Fruit",
  frambozen: "Groente & Fruit",
  bosbes: "Groente & Fruit",
  bosbessen: "Groente & Fruit",
  blauwe bessen: "Groente & Fruit",
  kers: "Groente & Fruit",
  kersen: "Groente & Fruit",
  pruim: "Groente & Fruit",
  pruimen: "Groente & Fruit",
  perzik: "Groente & Fruit",
  perziken: "Groente & Fruit",
  nectarine: "Groente & Fruit",
  nectarines: "Groente & Fruit",
  mango: "Groente & Fruit",
  ananas: "Groente & Fruit",
  kiwi: "Groente & Fruit",
  avocado: "Groente & Fruit",
  meloen: "Groente & Fruit",
  watermeloen: "Groente & Fruit",
  granaatappel: "Groente & Fruit",
  passievrucht: "Groente & Fruit",
  kokos: "Groente & Fruit",
  dadels: "Groente & Fruit",
  vijgen: "Groente & Fruit",
  // Groente & Fruit — verse kruiden
  peterselie: "Groente & Fruit",
  basilicum: "Groente & Fruit",
  koriander: "Groente & Fruit",
  munt: "Groente & Fruit",
  dille: "Groente & Fruit",
  bieslook: "Groente & Fruit",
  rozemarijn: "Groente & Fruit",
  tijm: "Groente & Fruit",
  salie: "Groente & Fruit",
  dragon: "Groente & Fruit",
  kervel: "Groente & Fruit",
  laurierblad: "Groente & Fruit",

  // Bakkerij & Brood
  brood: "Bakkerij & Brood",
  broodjes: "Bakkerij & Brood",
  volkoren: "Bakkerij & Brood",
  "volkoren brood": "Bakkerij & Brood",
  "wit brood": "Bakkerij & Brood",
  "bruin brood": "Bakkerij & Brood",
  casino: "Bakkerij & Brood",
  tijgerbrood: "Bakkerij & Brood",
  tortilla: "Bakkerij & Brood",
  "tortilla's": "Bakkerij & Brood",
  wraps: "Bakkerij & Brood",
  pita: "Bakkerij & Brood",
  pitabroodjes: "Bakkerij & Brood",
  naan: "Bakkerij & Brood",
  naanbrood: "Bakkerij & Brood",
  stokbrood: "Bakkerij & Brood",
  croissant: "Bakkerij & Brood",
  croissants: "Bakkerij & Brood",
  beschuit: "Bakkerij & Brood",
  crackers: "Bakkerij & Brood",
  knäckebröd: "Bakkerij & Brood",

  // Vlees & Vis
  kip: "Vlees & Vis",
  kipfilet: "Vlees & Vis",
  kippendij: "Vlees & Vis",
  kippenpoten: "Vlees & Vis",
  kippenbouten: "Vlees & Vis",
  kippenvleugels: "Vlees & Vis",
  "hele kip": "Vlees & Vis",
  kipschnitzel: "Vlees & Vis",
  gehakt: "Vlees & Vis",
  rundergehakt: "Vlees & Vis",
  "half-om-half gehakt": "Vlees & Vis",
  biefstuk: "Vlees & Vis",
  entrecote: "Vlees & Vis",
  rundvlees: "Vlees & Vis",
  varkensvlees: "Vlees & Vis",
  varkenshaas: "Vlees & Vis",
  schnitzel: "Vlees & Vis",
  spekjes: "Vlees & Vis",
  spek: "Vlees & Vis",
  bacon: "Vlees & Vis",
  worst: "Vlees & Vis",
  rookworst: "Vlees & Vis",
  braadworst: "Vlees & Vis",
  lam: "Vlees & Vis",
  lamsvlees: "Vlees & Vis",
  eend: "Vlees & Vis",
  kalkoen: "Vlees & Vis",
  zalm: "Vlees & Vis",
  zalmfilet: "Vlees & Vis",
  garnalen: "Vlees & Vis",
  tonijn: "Vlees & Vis",
  kabeljauw: "Vlees & Vis",
  pangasius: "Vlees & Vis",
  tilapia: "Vlees & Vis",
  vis: "Vlees & Vis",
  visfilet: "Vlees & Vis",
  haring: "Vlees & Vis",
  makreel: "Vlees & Vis",
  mosselen: "Vlees & Vis",
  scampi: "Vlees & Vis",
  inktvis: "Vlees & Vis",
  tofu: "Vlees & Vis",
  tempeh: "Vlees & Vis",

  // Kaas & Vleeswaren
  kaas: "Kaas & Vleeswaren",
  "geraspte kaas": "Kaas & Vleeswaren",
  "jong belegen": "Kaas & Vleeswaren",
  "oud kaas": "Kaas & Vleeswaren",
  parmezaan: "Kaas & Vleeswaren",
  "parmezaanse kaas": "Kaas & Vleeswaren",
  mozzarella: "Kaas & Vleeswaren",
  feta: "Kaas & Vleeswaren",
  geitenkaas: "Kaas & Vleeswaren",
  brie: "Kaas & Vleeswaren",
  camembert: "Kaas & Vleeswaren",
  roomkaas: "Kaas & Vleeswaren",
  "smeerkaas": "Kaas & Vleeswaren",
  cheddar: "Kaas & Vleeswaren",
  gruyère: "Kaas & Vleeswaren",
  gruyere: "Kaas & Vleeswaren",
  ham: "Kaas & Vleeswaren",
  "achterham": "Kaas & Vleeswaren",
  "katenspek": "Kaas & Vleeswaren",
  salami: "Kaas & Vleeswaren",
  chorizo: "Kaas & Vleeswaren",
  rookvlees: "Kaas & Vleeswaren",
  kipfilet_vleeswaren: "Kaas & Vleeswaren",
  filet_americain: "Kaas & Vleeswaren",

  // Zuivel & Eieren
  melk: "Zuivel & Eieren",
  halfvolle_melk: "Zuivel & Eieren",
  "halfvolle melk": "Zuivel & Eieren",
  "volle melk": "Zuivel & Eieren",
  karnemelk: "Zuivel & Eieren",
  ei: "Zuivel & Eieren",
  eieren: "Zuivel & Eieren",
  boter: "Zuivel & Eieren",
  roomboter: "Zuivel & Eieren",
  margarine: "Zuivel & Eieren",
  slagroom: "Zuivel & Eieren",
  room: "Zuivel & Eieren",
  kookroom: "Zuivel & Eieren",
  "creme fraiche": "Zuivel & Eieren",
  "crème fraîche": "Zuivel & Eieren",
  yoghurt: "Zuivel & Eieren",
  "griekse yoghurt": "Zuivel & Eieren",
  kwark: "Zuivel & Eieren",
  "zure room": "Zuivel & Eieren",
  ricotta: "Zuivel & Eieren",
  mascarpone: "Zuivel & Eieren",
  vla: "Zuivel & Eieren",
  pudding: "Zuivel & Eieren",
  "cottage cheese": "Zuivel & Eieren",
  "hüttenkäse": "Zuivel & Eieren",
  huttenkaas: "Zuivel & Eieren",

  // Kant-en-klaar & Salades
  hummus: "Kant-en-klaar & Salades",
  pesto: "Kant-en-klaar & Salades",
  tzatziki: "Kant-en-klaar & Salades",
  guacamole: "Kant-en-klaar & Salades",
  "kant-en-klaar": "Kant-en-klaar & Salades",
  maaltijdsalade: "Kant-en-klaar & Salades",
  soep: "Kant-en-klaar & Salades",

  // Diepvries
  diepvriesgroenten: "Diepvries",
  "diepvries spinazie": "Diepvries",
  "diepvries doperwten": "Diepvries",
  pizza: "Diepvries",
  ijsjes: "Diepvries",
  ijs: "Diepvries",
  friet: "Diepvries",
  frites: "Diepvries",
  oven_frites: "Diepvries",

  // Pasta, Rijst & Wereldkeuken
  pasta: "Pasta, Rijst & Wereldkeuken",
  spaghetti: "Pasta, Rijst & Wereldkeuken",
  penne: "Pasta, Rijst & Wereldkeuken",
  fusilli: "Pasta, Rijst & Wereldkeuken",
  macaroni: "Pasta, Rijst & Wereldkeuken",
  tagliatelle: "Pasta, Rijst & Wereldkeuken",
  farfalle: "Pasta, Rijst & Wereldkeuken",
  lasagnebladen: "Pasta, Rijst & Wereldkeuken",
  lasagne: "Pasta, Rijst & Wereldkeuken",
  rijst: "Pasta, Rijst & Wereldkeuken",
  basmatirijst: "Pasta, Rijst & Wereldkeuken",
  "jasmine rijst": "Pasta, Rijst & Wereldkeuken",
  "zilvervlies rijst": "Pasta, Rijst & Wereldkeuken",
  noodles: "Pasta, Rijst & Wereldkeuken",
  mie: "Pasta, Rijst & Wereldkeuken",
  bami: "Pasta, Rijst & Wereldkeuken",
  couscous: "Pasta, Rijst & Wereldkeuken",
  bulgur: "Pasta, Rijst & Wereldkeuken",
  quinoa: "Pasta, Rijst & Wereldkeuken",
  "rode linzen": "Pasta, Rijst & Wereldkeuken",
  linzen: "Pasta, Rijst & Wereldkeuken",
  kikkererwten: "Pasta, Rijst & Wereldkeuken",
  kokosmelk: "Pasta, Rijst & Wereldkeuken",
  sojasaus: "Pasta, Rijst & Wereldkeuken",
  ketjap: "Pasta, Rijst & Wereldkeuken",
  sambal: "Pasta, Rijst & Wereldkeuken",
  currypasta: "Pasta, Rijst & Wereldkeuken",
  tahini: "Pasta, Rijst & Wereldkeuken",
  sriracha: "Pasta, Rijst & Wereldkeuken",
  "tortilla chips": "Pasta, Rijst & Wereldkeuken",
  taco: "Pasta, Rijst & Wereldkeuken",
  tacoschelpen: "Pasta, Rijst & Wereldkeuken",
  kroepoek: "Pasta, Rijst & Wereldkeuken",
  woksaus: "Pasta, Rijst & Wereldkeuken",

  // Soepen, Sauzen & Kruiden
  tomatensaus: "Soepen, Sauzen & Kruiden",
  passata: "Soepen, Sauzen & Kruiden",
  "gepelde tomaten": "Soepen, Sauzen & Kruiden",
  tomatenpuree: "Soepen, Sauzen & Kruiden",
  bouillon: "Soepen, Sauzen & Kruiden",
  bouillonblokje: "Soepen, Sauzen & Kruiden",
  zout: "Soepen, Sauzen & Kruiden",
  peper: "Soepen, Sauzen & Kruiden",
  "zwarte peper": "Soepen, Sauzen & Kruiden",
  komijn: "Soepen, Sauzen & Kruiden",
  kurkuma: "Soepen, Sauzen & Kruiden",
  paprikapoeder: "Soepen, Sauzen & Kruiden",
  kaneelpoeder: "Soepen, Sauzen & Kruiden",
  kaneel: "Soepen, Sauzen & Kruiden",
  nootmuskaat: "Soepen, Sauzen & Kruiden",
  oregano: "Soepen, Sauzen & Kruiden",
  "italiaanse kruiden": "Soepen, Sauzen & Kruiden",
  kerrie: "Soepen, Sauzen & Kruiden",
  curry: "Soepen, Sauzen & Kruiden",
  cayennepeper: "Soepen, Sauzen & Kruiden",
  chilipoeder: "Soepen, Sauzen & Kruiden",
  chilivlokken: "Soepen, Sauzen & Kruiden",
  mosterd: "Soepen, Sauzen & Kruiden",
  mayonaise: "Soepen, Sauzen & Kruiden",
  mayo: "Soepen, Sauzen & Kruiden",
  ketchup: "Soepen, Sauzen & Kruiden",
  azijn: "Soepen, Sauzen & Kruiden",
  balsamicoazijn: "Soepen, Sauzen & Kruiden",
  wijnazijn: "Soepen, Sauzen & Kruiden",
  olijfolie: "Soepen, Sauzen & Kruiden",
  zonnebloemolie: "Soepen, Sauzen & Kruiden",
  olie: "Soepen, Sauzen & Kruiden",
  "extra vierge olijfolie": "Soepen, Sauzen & Kruiden",
  "sesamolie": "Soepen, Sauzen & Kruiden",
  vissaus: "Soepen, Sauzen & Kruiden",
  worcestersaus: "Soepen, Sauzen & Kruiden",
  tabasco: "Soepen, Sauzen & Kruiden",

  // Conserven & Granen
  havermout: "Conserven & Granen",
  muesli: "Conserven & Granen",
  cornflakes: "Conserven & Granen",
  ontbijtgranen: "Conserven & Granen",
  bloem: "Conserven & Granen",
  "zelfrijzend bakmeel": "Conserven & Granen",
  maizena: "Conserven & Granen",
  suiker: "Conserven & Granen",
  basterdsuiker: "Conserven & Granen",
  poedersuiker: "Conserven & Granen",
  vanillesuiker: "Conserven & Granen",
  bakpoeder: "Conserven & Granen",
  gist: "Conserven & Granen",
  "witte bonen": "Conserven & Granen",
  "kidney bonen": "Conserven & Granen",
  "zwarte bonen": "Conserven & Granen",
  "bruine bonen": "Conserven & Granen",
  "blik tomaten": "Conserven & Granen",
  "blik mais": "Conserven & Granen",

  // Broodbeleg & Ontbijt
  pindakaas: "Broodbeleg & Ontbijt",
  jam: "Broodbeleg & Ontbijt",
  honing: "Broodbeleg & Ontbijt",
  hagelslag: "Broodbeleg & Ontbijt",
  nutella: "Broodbeleg & Ontbijt",
  chocoladepasta: "Broodbeleg & Ontbijt",
  appelstroop: "Broodbeleg & Ontbijt",
  "chocopasta": "Broodbeleg & Ontbijt",
  vlokken: "Broodbeleg & Ontbijt",
  speculaas: "Broodbeleg & Ontbijt",

  // Snoep & Koek
  chocolade: "Snoep & Koek",
  koekjes: "Snoep & Koek",
  snoep: "Snoep & Koek",
  drop: "Snoep & Koek",
  stroopwafels: "Snoep & Koek",
  cake: "Snoep & Koek",
  taart: "Snoep & Koek",
  gevulde koeken: "Snoep & Koek",

  // Chips & Noten
  chips: "Chips & Noten",
  noten: "Chips & Noten",
  "pinda's": "Chips & Noten",
  pinda: "Chips & Noten",
  cashewnoten: "Chips & Noten",
  walnoten: "Chips & Noten",
  amandelen: "Chips & Noten",
  pistachenoten: "Chips & Noten",
  pecannoten: "Chips & Noten",
  macadamia: "Chips & Noten",
  pijnboompitten: "Chips & Noten",
  zonnebloempitten: "Chips & Noten",
  pompoenpitten: "Chips & Noten",
  sesamzaad: "Chips & Noten",
  lijnzaad: "Chips & Noten",
  chiazaad: "Chips & Noten",
  rozijnen: "Chips & Noten",
  "gemengde noten": "Chips & Noten",
  notenmix: "Chips & Noten",
  popcorn: "Chips & Noten",

  // Dranken
  water: "Dranken",
  "spa blauw": "Dranken",
  "spa rood": "Dranken",
  sap: "Dranken",
  sinaasappelsap: "Dranken",
  appelsap: "Dranken",
  jus: "Dranken",
  "d'orange": "Dranken",
  limonade: "Dranken",
  cola: "Dranken",
  fris: "Dranken",
  frisdrank: "Dranken",
  wijn: "Dranken",
  "rode wijn": "Dranken",
  "witte wijn": "Dranken",
  bier: "Dranken",

  // Koffie & Thee
  koffie: "Koffie & Thee",
  koffiebonen: "Koffie & Thee",
  koffiecups: "Koffie & Thee",
  thee: "Koffie & Thee",
  "groene thee": "Koffie & Thee",
  cacao: "Koffie & Thee",
  "chocomel": "Koffie & Thee",

  // Huishouden & Schoonmaak
  afwasmiddel: "Huishouden & Schoonmaak",
  wasmiddel: "Huishouden & Schoonmaak",
  allesreiniger: "Huishouden & Schoonmaak",
  schoonmaakmiddel: "Huishouden & Schoonmaak",
  keukenpapier: "Huishouden & Schoonmaak",
  keukenrol: "Huishouden & Schoonmaak",
  toiletpapier: "Huishouden & Schoonmaak",
  vaatwastabletten: "Huishouden & Schoonmaak",
  vuilniszakken: "Huishouden & Schoonmaak",
  aluminiumfolie: "Huishouden & Schoonmaak",
  bakpapier: "Huishouden & Schoonmaak",
  huishoudfolie: "Huishouden & Schoonmaak",

  // Persoonlijke Verzorging
  shampoo: "Persoonlijke Verzorging",
  tandpasta: "Persoonlijke Verzorging",
  douchegel: "Persoonlijke Verzorging",
  zeep: "Persoonlijke Verzorging",
  deodorant: "Persoonlijke Verzorging",
  scheermesjes: "Persoonlijke Verzorging",
  tissues: "Persoonlijke Verzorging",
  maandverband: "Persoonlijke Verzorging",
  tampons: "Persoonlijke Verzorging",

  // Baby & Kind
  luiers: "Baby & Kind",
  babyvoeding: "Baby & Kind",
  flesvoeding: "Baby & Kind",

  // Diervoeding
  kattenvoer: "Diervoeding",
  hondenvoer: "Diervoeding",
  kattenbrokken: "Diervoeding",
  kattengrit: "Diervoeding",
};

// In-memory cache for AI-categorized ingredients (persists for server lifetime)
const aiCategoryCache: Record<string, string> = {};

export const DEFAULT_CATEGORIES = [
  "Groente & Fruit",
  "Bakkerij & Brood",
  "Vlees & Vis",
  "Kaas & Vleeswaren",
  "Zuivel & Eieren",
  "Kant-en-klaar & Salades",
  "Diepvries",
  "Pasta, Rijst & Wereldkeuken",
  "Soepen, Sauzen & Kruiden",
  "Conserven & Granen",
  "Broodbeleg & Ontbijt",
  "Snoep & Koek",
  "Chips & Noten",
  "Dranken",
  "Koffie & Thee",
  "Huishouden & Schoonmaak",
  "Persoonlijke Verzorging",
  "Baby & Kind",
  "Diervoeding",
  "Overig",
];

/** Synchronous lookup — tries static map and AI cache only */
export function categorizeIngredientSync(name: string): string | null {
  const normalized = name.toLowerCase().trim();

  if (INGREDIENT_CATEGORY_MAP[normalized]) return INGREDIENT_CATEGORY_MAP[normalized];
  if (aiCategoryCache[normalized]) return aiCategoryCache[normalized];

  for (const [key, category] of Object.entries(INGREDIENT_CATEGORY_MAP)) {
    if (normalized.includes(key) || key.includes(normalized)) return category;
  }

  return null;
}

/** Cache a category from AI for future lookups */
export function cacheCategory(name: string, category: string) {
  aiCategoryCache[name.toLowerCase().trim()] = category;
}

/**
 * Categorize ingredient — returns from static map/cache, or "Overig" as fallback.
 * Use categorizeBatchWithAI for bulk AI categorization of unknowns.
 */
export function categorizeIngredient(name: string): string {
  return categorizeIngredientSync(name) || "Overig";
}
